export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER__REQUEST = "USER_REGISTER__REQUEST";
export const USER_REGISTER__SUCCESS = "USER_REGISTER__SUCCESS";
export const USER_REGISTER__FAIL = "USER_REGISTER_LOGIN_FAIL";

export const USER_DETAILS__REQUEST = "USER_DETAILS__REQUEST";
export const USER_DETAILS__SUCCESS = "USER_DETAILS__SUCCESS";
export const USER_DETAILS__FAIL = "USER_DETAILS_LOGIN_FAIL";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE__REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE__SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_LOGIN_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_LOGIN_FAIL";
